### ISSUE TITLE
error in SEIR infection module in tutorial

### ISSUE THREAD

**Issue by ThomasKraft** [statnet/EpiModel#443] opened 2020-08-07 17:59 UTC
The following page has been a useful guide to the extensive changes required in EpiModel v2: http://statnet.org/tut/EpiModel2.html#Introduction

On that page, under the "Full Example" section for "SEIR Extension Model", a function `infect2` is defined. This function does not work properly. To fix the problem, the code in the tutorial can simply be replaced by the properly working `infect2` function in the SEIR extension model on github: https://github.com/statnet/EpiModel/blob/ac02e1b8506c278a6f248e6061f761b08cb65e57/inst/EpiModel2/SEIRModuleExtension.R#L9

**Comment by smjenness** [comment] 2020-08-07 18:20
Can you provide more details how it does not work properly? It looks like they are the same function (as intended) on the HTML page and in the R file.

**Comment by ThomasKraft** [comment] 2020-08-07 19:57
The specific error thrown is "Error in `$<-.data.frame`(`*tmp*`, "finalProb", value = numeric(0)) : 
  replacement has 0 rows, data has 7 "

I believe this my have to do with the fact that the variable `transProb` is not defined in advance in the following line on the tutorial page:
    del$finalProb <- 1 - (1 - del$transProb)^del$actRate

The version of `infect2` on github is different at lines 26-28 and does the following:
    del$transProb <- inf.prob

If it would be helpful to reproduce the error, you can do so by pasting together all the code from the tutorial file and running netsim at the end with the updated modules as follows (the error does not occur if you replace `infect2` with the version on github):

```
## EpiModel 2.0:
# Update `$` operations to accessor functions

## Modified infection module
infect2 <- function(dat, at) {
  
  active <- get_attr(dat, "active")
  status <- get_attr(dat, "status")
  infTime <- get_attr(dat, "infTime")
  inf.prob <- get_param(dat, "inf.prob")
  act.rate <- get_param(dat, "act.rate")
  
  idsInf <- which(active == 1 & status == "i")
  nActive <- sum(active == 1)
  
  nElig <- length(idsInf)
  nInf <- 0
  
  if (nElig > 0 && nElig < nActive) {
    del <- discord_edgelist(dat, at)
    if (!(is.null(del))) {
      del$finalProb <- 1 - (1 - del$transProb)^del$actRate
      transmit <- rbinom(nrow(del), 1, del$finalProb)
      del <- del[which(transmit == 1), ]
      idsNewInf <- unique(del$sus)
      nInf <- length(idsNewInf)
      if (nInf > 0) {
        status[idsNewInf] <- "e"
        infTime[idsNewInf] <- at
        dat <- set_attr(dat, "status", status)
        dat <- set_attr(dat, "infTime", infTime)
      }
    }
  }
  
  dat <- set_epi(dat, "se.flow", at, nInf)
  
  return(dat)
}


## New disease progression module
progress2 <- function(dat, at) {
  
  active <- get_attr(dat, "active")
  status <- get_attr(dat, "status")
  
  ei.rate <- get_param(dat, "ei.rate")
  ir.rate <- get_param(dat, "ir.rate")
  
  ## E to I progression
  nInf <- 0
  idsEligInf <- which(active == 1 & status == "e")
  nEligInf <- length(idsEligInf)
  
  if (nEligInf > 0) {
    vecInf <- which(rbinom(nEligInf, 1, ei.rate) == 1)
    if (length(vecInf) > 0) {
      idsInf <- idsEligInf[vecInf]
      nInf <- length(idsInf)
      status[idsInf] <- "i"
    }
  }
  
  ## I to R progression
  nRec <- 0
  idsEligRec <- which(active == 1 & status == "i")
  nEligRec <- length(idsEligRec)
  
  if (nEligRec > 0) {
    vecRec <- which(rbinom(nEligRec, 1, ir.rate) == 1)
    if (length(vecRec) > 0) {
      idsRec <- idsEligRec[vecRec]
      nRec <- length(idsRec)
      status[idsRec] <- "r"
    }
  }
  
  dat <- set_attr(dat, "status", status)
  
  dat <- set_epi(dat, "ei.flow", at, nInf)
  dat <- set_epi(dat, "ir.flow", at, nRec)
  dat <- set_epi(dat, "e.num", at, sum(active == 1 & status == "e"))
  dat <- set_epi(dat, "r.num", at, sum(active == 1 & status == "r"))
  
  return(dat)
}

nw <- network_initialize(n = 500)
est <- netest(nw, formation = ~ edges, target.stats = 150,
              coef.diss = dissolution_coefs(~offset(edges), 10))
param <- param.net(inf.prob = 0.5, act.rate = 2, ei.rate = 0.01, ir.rate = 0.005)
init <- init.net(i.num = 10)
control <- control.net(type = NULL, nsteps = 100, nsims = 1, 
                       infection.FUN = infect2, progress.FUN = progress2)
netsim(est, param, init, control)
```

* Also note that at the very end of the tutorial for the SEIR extension model the `control.net` function includes "infect" and "progress" whereas the tutorial implies that it should be running the updated modules "infect2" and "progress2"

**Comment by smjenness** [comment] 2020-08-07 20:45
@ThomasKraft : this should be updated online now. Thanks for finding this!

@andsv2 : please do a comprehensive check of this document and the associated R scripts online before closing the issue.

**Comment by ThomasKraft** [comment] 2020-08-10 18:32
One additional concern: the custom `progress2` function in the SEIR module moves sequentially through the states, first handling e -> i transitions, and then i -> r transitions. As far as I can tell, this behavior makes it possible for an individual to move from e -> r within the same timestep. I'm not sure if this is desired behavior, but if not, 2 possible solutions are:

1) reversing the order so that i->r precedes e->r transitions.
2) using setdiff() in describing who is eligible for a i->r transition.

**Comment by smjenness** [comment] 2020-08-13 10:15
that's true, although outside the scope of this migration doc (our goal is not to demonstrate a full research-level model here)

**Closed** 2020-09-22 14:21 UTC
