### ISSUE TITLE
edges_correct: R crashing at conditional logic between tgl = TRUE/FALSE

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModel#351] opened 2020-03-20 14:05 UTC
Related to commit https://github.com/statnet/EpiModel/pull/347: In edges correct, ID's of nodes need to be looked up in two ways: if `tgl = FALSE`, IDS are returned using `idgroup` function which pulls vertex attributes - in this case group; if however `tgl = TRUE`, group assignment is now pulled_ from an attribute tracker created previously. 

This change causes R to crash when running `netsim`. The behavior is NOT experienced when running `resim_nets` outside of `netsim`.

Sample script:

```num1 <- num2 <- 500
nw <- network.initialize(num1 + num2, directed = FALSE)
nw <- set.vertex.attribute(nw, "group", rep(1:2, each = num1))
formation <- ~edges + nodefactor("group") + nodematch("group")
target.stats <- c(400, 200, 0)
coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 100)
est <- netest(nw, formation, target.stats, coef.diss)

# Parameters
init <- init.net(i.num = 20, i.num.g2 = 20)
param <- param.net(inf.prob = 0.1, inf.prob.g2 = 0.1, act.rate = 5)
control <- control.net(type = "SI", nsteps = 100, nsims = 5, tgl = TRUE)

sim <- netsim(est, param, init, control)
```

**Comment by andsv2** [comment] 2020-03-20 14:09
@smjenness when you have time could you see if you can replicate this behavior on your end.

**Comment by smjenness** [comment] 2020-03-20 14:15
Updating the example so it is fully reproducible.

```r
library("EpiModel")
num1 <- num2 <- 500
nw <- network.initialize(num1 + num2, directed = FALSE)
nw <- set.vertex.attribute(nw, "group", rep(1:2, each = num1))
formation <- ~edges + nodefactor("group") + nodematch("group")
target.stats <- c(400, 400, 0)
coef.diss <- dissolution_coefs(dissolution = ~offset(edges), duration = 100)
est <- netest(nw, formation, target.stats, coef.diss)

# Parameters
init <- init.net(i.num = 20, i.num.g2 = 20)
param <- param.net(inf.prob = 0.1, inf.prob.g2 = 0.1, act.rate = 5)
control <- control.net(type = "SI", nsteps = 100, nsims = 5, tgl = TRUE)

sim <- netsim(est, param, init, control)
```

**Comment by smjenness** [comment] 2020-03-20 14:34
This is just a problem with the ERGM because it is an overparameterized model (if no edges are between groups then the nodefactor for either group must equal the edges). Just remove the nodefactor term from the model.

```r
formation <- ~edges + nodematch("group")
target.stats <- c(400, 0)
```

**Comment by smjenness** [comment] 2020-03-22 15:22
@andsv2 I assume this is fixed now. Closing for you. If not fixed, re-open.

**Closed by smjenness** 2020-03-22 15:22 UTC
